device_name: <what should this device be called?>
mqtt:
  broker: <your broker IP>
  port: <default port is: 1883>
  username: <mqtt username>
  password: <mqtt password>
  state_topic: <where to push the state of the relay, example for 'state' it will be 'I2C/device_name/state'>
  command_topic: <where to grab the command for the relay,example for 'cmnd' it will be 'I2C/device_name/cmnd>
homeassistant:
  discovery: <"true" if you want autodiscovery for HomeAssistant>
  discovery_prefix: <by default it should be homeassistant>
i2c:
  device_address: <read it out with 'i2cdetect -y 1', in my case it is 0x10>
  register_address:  <nothing to configure here actually, relay1 is 0x01, and so on>
    1: 0x01
    2: 0x02
    3: 0x03
    4: 0x04
